"""Regenerate materialized notebook library modules.

Usage:
    python activation_oracles_extensions/materialize_notebook_functions.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path


LIBRARY_CELL_MARKER = "# @title Library Code"

ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = ROOT / "materialized"

NOTEBOOK_TO_OUTPUT = {
    "activation_oracle_demo.ipynb": "activation_oracle_demo_lib.py",
    "multilayer_activation_oracle_demo.ipynb": "multilayer_activation_oracle_demo_lib.py",
}


def resolve_experiments_dir() -> Path:
    """Find activation_oracles/experiments from activation-oracles repo root."""
    env_override = os.environ.get("ACTIVATION_ORACLES_EXPERIMENTS_DIR")
    if env_override:
        path = Path(env_override).expanduser().resolve()
        if path.exists():
            return path
        raise FileNotFoundError(
            "ACTIVATION_ORACLES_EXPERIMENTS_DIR is set but does not exist: "
            f"{path}"
        )

    candidates = [
        ROOT.parent / "activation_oracles" / "experiments",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate

    searched = "\n  - ".join(str(c) for c in candidates)
    raise FileNotFoundError(
        "Could not locate activation_oracles/experiments.\n"
        "Set ACTIVATION_ORACLES_EXPERIMENTS_DIR or place the repo in one of:\n"
        f"  - {searched}"
    )


def extract_library_cell(notebook_path: Path) -> str:
    data = json.loads(notebook_path.read_text())
    for cell in data.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        src = "".join(cell.get("source", []))
        if LIBRARY_CELL_MARKER in src:
            return src.strip() + "\n"
    raise ValueError(f"Could not find library code cell in {notebook_path}")


def header(notebook_path: Path) -> str:
    try:
        source_display = notebook_path.relative_to(ROOT.parent)
    except ValueError:
        source_display = notebook_path
    return (
        '"""Auto-generated from notebook library code.\n\n'
        f"Source notebook: {source_display}\n"
        "Do not edit this file manually; regenerate with:\n"
        "  python activation_oracles_extensions/materialize_notebook_functions.py\n"
        '"""\n\n'
    )


def main() -> None:
    experiments_dir = resolve_experiments_dir()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for notebook_name, output_name in NOTEBOOK_TO_OUTPUT.items():
        notebook_path = experiments_dir / notebook_name
        if not notebook_path.exists():
            raise FileNotFoundError(f"Missing notebook: {notebook_path}")

        content = extract_library_cell(notebook_path)
        output_path = OUTPUT_DIR / output_name
        output_path.write_text(header(notebook_path) + content)
        print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()

